// App-level aliases over the generated database types.
//
// lib/database.types.ts is regenerated by `npm run db:types` and must not be
// edited by hand — put anything hand-written here instead.

import type { Database, Tables, TablesInsert, Enums } from './database.types';

export type { Database };

export type Profile = Tables<'profiles'>;
export type Anime = Tables<'anime'>;
export type UserAnime = Tables<'user_anime'>;
export type Follow = Tables<'follows'>;
export type Recommendation = Tables<'recommendations'>;
export type Activity = Tables<'activity'>;

export type AnimeInsert = TablesInsert<'anime'>;

export type AnimeStatus = Enums<'anime_status'>;
export type Sentiment = Enums<'sentiment'>;
export type ActivityType = Enums<'activity_type'>;

// A user_anime row that has been placed in the ranking. The migration's
// user_anime_ranked_consistent check guarantees these three columns are either
// all null or all set, which the generated types cannot express on their own.
export type RankedAnime = UserAnime & {
  sentiment: Sentiment;
  rank_position: number;
  score: number;
};

/**
 * Best available display title. AniList frequently has no English title -- of
 * three Frieren results, one had none -- so romaji is the fallback rather than
 * an afterthought.
 */
export function animeTitle(anime: Pick<Anime, 'title_english' | 'title_romaji'>): string {
  return anime.title_english ?? anime.title_romaji ?? 'Untitled';
}

export function isRanked(row: UserAnime): row is RankedAnime {
  return row.sentiment !== null && row.rank_position !== null && row.score !== null;
}
