// App-level aliases over the generated database types. database.types.ts is
// regenerated by `npm run db:types`; hand-written types go here instead.

import type { Database, Tables, TablesInsert, Enums } from './database.types';

export type { Database };

export type Profile = Tables<'profiles'>;
export type Anime = Tables<'anime'>;
export type UserAnime = Tables<'user_anime'>;
export type Follow = Tables<'follows'>;
export type Recommendation = Tables<'recommendations'>;
export type Activity = Tables<'activity'>;

export type AnimeInsert = TablesInsert<'anime'>;

export type AnimeStatus = Enums<'anime_status'>;
export type Sentiment = Enums<'sentiment'>;
export type ActivityType = Enums<'activity_type'>;

// A ranked user_anime row. The user_anime_ranked_consistent check guarantees
// these three are all null or all set; the generated types cannot express that.
export type RankedAnime = UserAnime & {
  sentiment: Sentiment;
  rank_position: number;
  score: number;
};

/** Best display title; AniList often has no English one, so romaji is the fallback. */
export function animeTitle(anime: Pick<Anime, 'title_english' | 'title_romaji'>): string {
  return anime.title_english ?? anime.title_romaji ?? 'Untitled';
}

export function isRanked(row: UserAnime): row is RankedAnime {
  return row.sentiment !== null && row.rank_position !== null && row.score !== null;
}
